### ISSUE TITLE
Use numeric codes instead of alphanumeric

### ISSUE THREAD

**Issue by craigloftus** [regulusweb/ucsc-tz-labor#19]
Numeric only is easier to input.

Can probably drop the `#` as well.

**Comment by dajeong265** [comment]
Initially, I had thought the digit has to be large enough so that we have a unique ID for all jobs/applications, etc. But in the backend data tables, we're not using these 6 digit codes for any purpose, rather we use the data table row IDs to define a unique job, and an application, and for linking across the data tables. 

To make user experience better, what will be the implication of using a 4 digit code and then refresh them again every month or so (or when we run out of all 10000 combinations)? I don't expect there will be more than 10,000 postings per month even if when I go into a really optimistic full scale. As long as a worker doesn't to apply for a job that was posted a month ago or earlier and then the feedback/review survey are happening within a week or two weeks or so, shouldn't we be fine?

Alternatively, can we start with 3 digits, and then add a 4th digit when we run out of 1000 combinations, and then add a 5th digit, etc?

We can mix the two methods (i.e. refreshing + iteratively adding a digit) as well. 

Let me know your thoughts.

**Comment by craigloftus** [comment]
You're right that the codes are only used for looking up records based on incoming messages.

I assume you're only thinking about this because you've witnessed issues with using the 6 digit codes? If so, before considering a change it would be important to try to establish that it is the length of the codes that is the issue, rather than the use of codes generally.

I could implement the code generation such that it grows if a generated code collides with an existing one (we already have collision checking), but it wouldn't be worth the added complexity unless the motivation was strong.

I'm not sure that the idea of refreshing codes after 1 month is a good idea; this would effectively 'close' things after a month without communicating that to employers and workers... communicating that the posting was now closed would further add to the implementation complexity.

**Comment by dajeong265** [comment]
There were a few issues. Suppose we say "To apply, reply: WORK 123456."

One mistake they do is to send a text "WORK" to a phone number 123456. We can partially address this problem by removing the space, "To apply, reply: WORK123456"

Another problem was that they are doing this in a feature phone, so they are not seeing the codes while they are typing (unlike a smart phone that displays all incoming/outgoing msgs side by side). And 6 digit is too much to remember at a time. So, yes, in that sense this is a binding constraint. 

As to your point about whether the problem is the use of codes generally (not necessarily the length of the code), are you suggesting any other solution that does not involve using a code? 

I discussed with my local staff and farmers and among the multiple options (laid out below), it seems what we currently have (i.e. option 5 - keyword+numeric code without space in between) is the best way to go. 
option 1: reply: WORK #km9p
option 2: reply: WORK km9p
option 3: reply: WORK #w982101
option 4: reply: WORK w982101
option 5: reply: WORK982101

And I think option 5 is even better if we have only 3-4 digits. What do you think?

Ok. It doesn't have to be refreshing codes after 1 month. We could potentially refresh every 2 months or so. These jobs are for a few days of work, and in fact, we give an option up to 3 days later for "when does this job start." So, I don't expect any job posting is valid after a month or so. As long as this is true, I don't see the need to communicate it to the employers and workers. Why should we tell them that the job they posted 1 month or 2 month ago are invalid? We can say in the confirmation message, for example

`Okay. We'll forward offers to you soon. When you've filled the position reply: Close [[state.vars.recruit_code]]. This posting will be closed in 30 days automatically`

Let me know what you think and we can make a decision.

**Comment by craigloftus** [comment]
Okay. I think I can make this change (assuming the codes are cleaned out manually) and the change to the close service in the time remaining, but that will be it. I'll make a start in the morning.

**Comment by dajeong265** [comment]
Sounds good, please go ahead and implement both changes. 

What do you mean by "assuming the codes are cleaned out manually"?

**Comment by dajeong265** [comment]
Ok. let me know what the best way it is. 

But, I am not following why we have to do anything with the data tables because the numeric codes are all generated from the java script codes in Github?

My thought process is like this:
Suppose we use a 4 digit code, xxxx. It can be used to post 10,000 jobs, or 9,000 jobs assuming the first digit has to be 1 or greater. So, we draw any number from 1000, 1001, 1002, 1003, ..., 9999. I presume it'll take a few months or a year to exhaust the 9000 combinations. But on a second thought, instead of drawing a random number, how about we start the number in an ascending order? And then, once we hit 9999, then we can start using the number 1000 again. Do you see any downside here?

When I was merging recruit, offer, feedback, and review data tables, I didn't have to use any of the numeric codes, but I used the rowIDs to merge everything. So I think it's fine to reuse the codes. Let me know if I am not understanding what the problem is.

**Comment by craigloftus** [comment]
I've already implemented and deployed a new approach to start with short codes and grow over time.

Straightforward enumeration is rarely a good idea for codes you want users to input as it makes it much more likely that small typos will still retrieve a valid record.

The reason for clearing the old codes is because the user inputs the codes to look up records...

**Comment by craigloftus** [comment]
I've implemented a recurring service to squash old codes. It runs every day and clears any codes which are more than 30 days old.

https://telerivet.com/p/findjob/service/SVdf9822338ec7b9c7/edit

We don't have any 30 day old records yet, so I've tested the code as best I can without messing bunch of more recent records (I just messed with some of yours).

**Comment by dajeong265** [comment]
Hi Craig, sorry to bother but this is little urgent, because the application is not working as expected. I just posted a job with my test phone (that you know of) which gave the job code of KAZI 795. But with my other phone (+255785921343) I am not able to apply for this job. I am getting an error message. 

Could you fix this ASAP, there are people who posted a job a half an hour ago.

**Comment by dajeong265** [comment]
For the same reason, the FUNGA 795 is not working. Basically it thinks [[$recruit_code]] is empty.

**Comment by dajeong265** [comment]
Ok. I temporarily fixed the problem. By manually replacing 6 by 3 in the `parse_code` function below. But we have to make it as a function of the number of digits, or why can't we use regexr to extract the numeric portion?  

function parse_code(content) {
    matches = content.match(/(\d{**3**})$/);

    if (matches) {
        return matches[1];
    }
    else {
        return false;
    }
};

**Comment by craigloftus** [comment]
I've updated it to `/(\d{3,})$/` (note the extra comma), so this now matches 3 or more digits at the end of the message.
