### ISSUE TITLE
Importing Contacts.csv into the Contacts page

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#22]
I am just having trouble getting the import of contacts work. 

When I first clicked on "export" in the [contacts page](https://telerivet.com/p/2037d5f9/contacts), it downloads Contacts.csv. The file contained the some variables recorded by Telerivet, for example, Last Heard From, Last Contacted, Time Created, etc. 

When I add new rows to the downloaded Contacts.csv, and then try to import them back, all the column headings except name and phone number were not recognized. I did not proceed further from there, so I didn't get to test whether uploading a file would replace the existing list, or simply an append, etc. 

Overall, I am just curious of this import behavior, and was wondering if you could have a look and try

**Comment by craigloftus** [comment]
When importing it disregards your header row completely. The reason you see the name and phonenumber columns is because they are required for the import.

If you click the "(Unknown)" at the top of each column it lets you associate that column with a contact property.

In terms of update/append, it uses the phonenumbers to match existing contacts and updates those when found, otherwise it will create new contacts.

**Comment by dajeong265** [comment]
Verified.
