### ISSUE TITLE
Waiting time of 10 minutes for RECRUIT service

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#44]
Could you see this conversation at 5:28pm EAT?
https://telerivet.com/p/2037d5f9/contact/CT57df3e34f84fbdd6

Joseph Kissiri was trying to confirm his recruitment details by replying 1, but the system doesn't recognize it. It was delivered from Joseph's  phone on time, but it was not received within 10 minutes by the router phone. Is it why the system doesn't recognize the reply? 

If I want it to set the waiting time to be 15 minutes. I just can edit the service directly?

**Comment by craigloftus** [comment]
Yes, it is because it exceeded the time limit.

And yes, you can just change the times in the service definitions to whatever you think works best.

**Comment by dajeong265** [comment]
Thanks for the confirmation.

**Comment by dajeong265** [comment]
I set everything to be 15 minutes for now, but could you quickly explain the implications of setting it as "no time limit"?

How does the logic currently handle conflicting services in action?

**Comment by craigloftus** [comment]
With sms there isn't any conflict handling because each message has no context to allow you to resolve conflicts, so a contact can only be interacting with one service at a time; this was the motivation for using codes to initiate services when the contact is ready to do so.

If no time limit is set when `waiting for a response` then it will just keep waiting for the first message from that contact to come in, even if that is a response to a completely different message.
