### ISSUE TITLE
Implement survey service

### ISSUE THREAD

**Issue by craigloftus** [regulusweb/ucsc-tz-labor#8]
Implement an initial survey service to be scheduled for sending to follow up on farmer requests:

- [ ] Check for active state on the target contact
- [ ] Re-schedule if currently active
- [ ] Retrieve request based on the service context
- [ ] Send farmer survey message, asking for worker code that was hired (?)
- [ ] Wait for response and record result in a separate data table

**Comment by craigloftus** [comment]
@dajeong265 When it comes to asking the farmer which worker(s) they hired, I'm not 100% sure how to get that to work nicely.

I can't do something like "1 for Fred Fredrickson, 2 for Joe Smoothtown, 3 for Brian Sheeple" because we would quickly run out of space in the sms.

Even something like "1 for #kb, 2 for #7q, 3 for #lk" would run out of space if a particularly good job received a lot of offers, and it isn't particularly usable anyway... the recruiter would have to go back and refer to each offer sms.

Also, presumably we want to know about multiple accepted offers?

I could do it for each "accept" response, and then it is just a case of, did you hire this person and what rating would you give them? Potentially the farmer would be receive quite a few sms requests in a short space of time though.

**Comment by craigloftus** [comment]
@dajeong265 So, I've implemented the last approach I describe, as I don't see any alternatives, and @solarissmoke pointed out that there aren't likely to be too many workers per job. So with the approach I have implemented you will get the following message at a configurable time after accepting an offer:

```
You recently accepted an offer from Fred Frederickson. To let us know what you thought of them, reply: Survey #ya

> Survey #ya

If you hired Fred Frederickson, how did they do? Reply with 1 - 5 where 1 is bad and 5 is great.
> 3

Thanks. We hope you make use of the service again.
```

**Comment by craigloftus** [comment]
The other thing to think about is in what context the survey reminders make sense? If we end up sending users multiple surveys, to then send multiple reminders would likely only frustrate users?

**Comment by dajeong265** [comment]
There are three stages in the recruiting process that are relevant to us. 
1. the number of offers a recruiter receives
2. the number of offers a recruiter "accepts" (i.e. currently this action sends the worker's name and phone number to the recruiter)
3. the number of workers a recruiter eventually hire which can be different from the number of offers a recruiter quasi-"accepts", because "accept" doesn't mean they hired the worker.

Through Telerivet app, we observe 1 and 2, but we don't observe 3. In the survey data where I interviewed 1600 farmers in the Kilimanjaro region, the median number of workers a recruiter hired is mostly 1-4 for a given task of farming (conditional on hiring). But about 10% of recruiters hire 6-10 workers at a time, and a few outliers recruiters hire up to 20. But often times a recruit does not get involved in a hiring decision of all workers they hire. For example, a recruiter would talk with primary workers first, and tell them how many workers are needed, and the primary workers will bring other workers to the farm (especially if a recruiter is asking for more than 10 workers). I expect this behavior will be similar in the app, too. I don't expect a recruiter "accepts" (or views) more than 10 offers for example. (Speaking of which, the word "accept" could be a little confusing. Could we say "view", because it literally means you're viewing the worker's contact and names). 

To answer your question:
1. I was thinking of a survey conditional on their response sequentially, instead of sending multiple surveys at a time. See my example below.
2. Hence, there will be only one reminder per job post. 

You received names & contacts from 10 workers for the job post you made on [2018.06.23]. We're going to ask you which worker you hired. Did you hire Fred Frederickson? Reply 1 if yes 0 if no. 
>1
Did you hire DJ? Reply 1 if yes 0 if no. 
>0
Did you hire Jennifer? Reply 1 if yes 0 if no. 
>1

We want to now ask your satisfaction. Would you recommend Fred Frederickson to other recruiter? Reply with 1 - 5 where 1 is least likely and 5 is most likely.
> 3
Would you recommend Jennifer to other recruiter? Reply with 1 - 5 where 1 is least likely and 5 is most likely.
> 2

Notice in the above example Jennifer is skipped.

**Comment by dajeong265** [comment]
Another thing is that I'd like this survey with workers too, so that we can cross check.

For example, 
``` 
you applied to a job posted by [DJ] on [2018.06.30]. Reply 1 if you were hired and 0 if you were not.
```

**Comment by dajeong265** [comment]
Your suggestion sounds good to me. So the list of workers being mentioned in the messages should be only those workers whom employers "viewed", not every applicant. Please go ahead and implement them.

**Comment by dajeong265** [comment]
Another thing is that could you add this to the post-hiring survey questions:

How much did you end up paying the worker(s) per $[[payment]]?

**Comment by craigloftus** [comment]
Can you provide the final list of questions for the post-hiring survey?

**Comment by craigloftus** [comment]
I really need a final list of questions on this so we can sign off the work to date before moving onto the `time permitting` tasks.

**Comment by dajeong265** [comment]
For now, yes, these questions are good. And then I can add other questions later if I want. 

1. Would you recommend [[$name]] to someone else? Reply 0 if you didn't hire them, and 1 to 5, for unlikely to very likely.

2. How much did you end up paying your workers per $[[payment]]?

3. Were there other workers you hired outside of the system? Reply 0 for No and 1 for Yes.

**Comment by dajeong265** [comment]
Another question I have is that I was trying to update View 1_swahili according to View 1. I think it's easier If I delete View 1_swahili and then copy it off of View 1, but I am worried that the unique identifier of the service codes being changed. 

Do you mind updating View 1_swahili directly? The translations are here. 
https://docs.google.com/spreadsheets/d/1SF909TZAY-3pNtjTLiPzbov-UsPsfGBxH9R-7MTRPYs/edit#gid=0

**Comment by craigloftus** [comment]
I've updated `View 1_swahili`

**Comment by craigloftus** [comment]
I've updated the survey (english and swahili) to include the questions listed above. The swahili variant will need some additional translation.
